version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: chatter_box_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
